version: '3.8'

services:
  web:
    build: .
    container_name: football_transfermarkt_backend
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
