# Generated by Django 5.1.4 on 2025-01-09 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Team Name')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('foundation_year', models.PositiveIntegerField(verbose_name='Foundation Year')),
                ('stadium', models.CharField(max_length=100, verbose_name='Stadium')),
                ('coach', models.CharField(max_length=100, verbose_name='Coach')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team_photos/', verbose_name='Team Photo')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('birth_date', models.DateField(verbose_name='Date of Birth')),
                ('nationality', models.CharField(max_length=50, verbose_name='Nationality')),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DF', 'Defender'), ('MF', 'Midfielder'), ('FW', 'Forward')], max_length=2, verbose_name='Position')),
                ('jersey_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Jersey Number')),
                ('goals_scored', models.PositiveIntegerField(default=0, verbose_name='Goals Scored')),
                ('assists', models.PositiveIntegerField(default=0, verbose_name='Assists')),
                ('matches_played', models.PositiveIntegerField(default=0, verbose_name='Matches Played')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='player_photos/', verbose_name='Player Photo')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='teams_and_players.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
