# Generated by Django 5.1.4 on 2025-01-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='player_photos/', verbose_name='Player Photo'),
        ),
    ]
