# Generated by Django 5.1.4 on 2025-01-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team_photos/', verbose_name='Team Photo'),
        ),
    ]
